Update glob
Fixes a type issue introduced in `@types/node 20.12.11` [1]:

```
node_modules/path-scurry/dist/cjs/index.d.ts:117:31 - error TS2720: Class 'PathBase' incorrectly implements class 'Dirent'. Did you mean to extend 'Dirent' and inherit its members as a subclass?
  Property 'parentPath' is missing in type 'PathBase' but required in type 'Dirent'.

117 export declare abstract class PathBase implements Dirent {
                                  ~~~~~~~~

  node_modules/@types/node/fs.d.ts:247:9
    247         parentPath: string;
                ~~~~~~~~~~
    'parentPath' is declared here.
```

Bump glob, which includes path-scurry as a dependency:

```
$ npm ls path-scurry
@govuk-frontend/repository@ /Users/oliver.byford/Code/govuk-frontend
└─┬ @govuk-frontend/lib@ -> ./shared/lib
  └─┬ glob@10.3.10
    └── path-scurry@1.10.1
```

[1]: https://github.com/isaacs/path-scurry/issues/18