Switch back to default Jest test environment
We’re having issues with html-validate rejecting its own schema after updating to Jest 30 [^1]:

```
UserError: Element metadata is not valid: /form/attributes/action/enum/0: type must be string

    at new SchemaValidationError (node_modules/html-validate/src/error/schema-validation-error.ts:34:3)
    at MetaTable.loadFromObject (node_modules/html-validate/src/meta/table.ts:97:11)
    at loadEntry (node_modules/html-validate/src/config/config.ts:362:15)
    at Config.getMetaTable (node_modules/html-validate/src/config/config.ts:371:19)
    at Config.resolveData (node_modules/html-validate/src/config/config.ts:613:26)
    at Config.resolve (node_modules/html-validate/src/config/config.ts:596:28)
    at StaticConfigLoader._resolveConfig (node_modules/html-validate/src/config/loaders/static.ts:116:19)
    at StaticConfigLoader.getConfigFor (node_modules/html-validate/src/config/loaders/static.ts:75:16)
    at HtmlValidate.getConfigFor (node_modules/html-validate/src/htmlvalidate.nodejs.ts:624:36)
    at HtmlValidate.validateSource (node_modules/html-validate/src/htmlvalidate.nodejs.ts:161:29)
    at HtmlValidate.validateString (node_modules/html-validate/src/htmlvalidate.nodejs.ts:106:15)
    at packages/govuk-frontend/src/govuk/components/components.template.test.js:84:37
    at Array.map (<anonymous>)
    at Object.<anonymous> (packages/govuk-frontend/src/govuk/components/components.template.test.js:66:39)
```

For reasons we don’t understand, the issue disappears if we switch back to using Jest’s default test environment.

We opted to use jest-environment-node-single-context in preparation for using Dart Sass in 1ae2bf6 (#3191). However, this guidance only seems to apply to Dart Sass’ JS library and we’re using sass-embedded as of 46c8e1c (#3164). Either way, all of the tests seem to pass without it.

[^1]: Specifically, the issue occurs when using jest@30.0.0-beta.4 or later.