Fix character count when ID starts with a number
Although it’s valid to start an ID with a number, the lack of quotes makes this an invalid CSS selector when interpolated with an ID that starts with a number, and an error is thrown:

> DOMException: Failed to execute 'querySelector' on 'Element': '[id=1_more-detail-info]' is not a valid selector.

This is because attribute values are either `ident-tokens` or `string-tokens` [1]. Omitting the quotes means that the atrribute value is treated as an ident-token, which may not start with a number [2].

Quoting the value means it’s treated instead as a string-token, which can start with a number [3].

Ideally we’d be using `document.getElementById` to get the count message, but we’ve previously decided that would be a breaking change as it means the lookup is no longer scoped to the $module [4].

[1]: https://www.w3.org/TR/selectors/#attribute-representation
[2]: https://www.w3.org/TR/css-syntax-3/#ident-token-diagram
[3]: https://www.w3.org/TR/css-syntax-3/#string-token-diagram
[4]: https://github.com/alphagov/govuk-frontend/pull/1843#issuecomment-650162310